services:
  # postgres:
  #   image: 'postgres:latest'
  #   environment:
  #     - 'POSTGRES_DB=mydatabase'
  #     - 'POSTGRES_PASSWORD=secret'
  #     - 'POSTGRES_USER=myuser'
  #   ports:
  #     - '5432'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
  # neo4j:
  #   image: 'neo4j:latest'
  #   environment:
  #     - 'NEO4J_AUTH=neo4j/notverysecret'
  #   ports:
  #     - '7687'
