-- spring.sql.init.platform=postgresql
DROP TABLE IF EXISTS houses;
CREATE TABLE houses (
    id BIGINT generated by default as identity,
    address VARCHAR(255),
    price INT,
    PRIMARY KEY (id)
);