name: CD-CloudRun

on:
    release:
      types: [released, edited]

jobs:
  cd-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4' #GCP required

    - name: Set the environment variable
      run: echo WIP=${{ secrets.GCP_PROJECT_ID }} >> $GITHUB_ENV

    - name: Check the environment variable
      run: echo $WIP

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/999999/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: ${{ secrets.GCP_SERVICEACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'pivotalspring-prod'
        region: us-west1
        image: 'dbeauregard/pivotalspring:0.0.1-SNAPSHOT'

    - name: 'Show output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'