name: CD to CloudRun

on:
  push: 
    tags: 
      - "**"
  workflow_dispatch:
      inputs:
          tag:
              description: 'the tag/version'
              required: true
              type: string
              default: 'v1.0.0-102-SNAPSHOT'

jobs:
  cd-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4' #GCP required

    - name: 'Get Variables'
      run: |
        echo "ref_name: ${{ github.ref_name }}"
        echo "input tag: ${{inputs.tag}}"

        # Prefer the input tag, fallback to github.ref_name if empty
        START_TAG="${{ inputs.tag != '' && inputs.tag || github.ref_name }}"

        DOCKER_TAG=`echo $START_TAG | sed 's/^v//'`
        GCP_TAG=`echo $START_TAG | sed 's/\./-/g' | awk '{print tolower($0)}'`
        echo "Docker TAG: $DOCKER_TAG"
        echo "GCP TAG: $GCP_TAG"
        echo "START_TAG=$START_TAG" >> $GITHUB_ENV
        echo "GCP_TAG=$GCP_TAG" >> $GITHUB_ENV
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

    - name: 'Set Variables in cloud run config'
      run: |
        sed -i "s/{VERSION}/$DOCKER_TAG/g" server/cloudrun.yaml
        sed -i "s/{VERSION_GCP}/$GCP_TAG/g" server/cloudrun.yaml
        cat server/cloudrun.yaml

    - uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: ${{ secrets.GCP_SERVICEACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'pivotalspring-server-prod'
        metadata: server/cloudrun.yaml
        region: us-west1 # Still needed with yaml
        # image: 'docker.io/dbeauregard/pivotalspring-server:0.0.1-SNAPSHOT'

    - name: 'Show output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'

    - name: Set the Summary
      if: always()
      id: set-step-summary
      run: |
        echo "TAG: $START_TAG"  >> $GITHUB_STEP_SUMMARY
        echo "URL: ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY