name: CD to CloudRun

on:
  push: 
    tags: 
      - "**"

jobs:
  cd-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4' #GCP required

    - name: print-env
      run: |
        echo ${{ github.event.release.tag_name }}
        echo $GITHUB_ENV

    - uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: ${{ secrets.GCP_SERVICEACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'pivotalspring-server-prod'
        metadata: server/cloudrun.yaml
        region: us-west1 # Still needed with yaml
        # image: 'docker.io/dbeauregard/pivotalspring-server:0.0.1-SNAPSHOT'

    - name: 'Show output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'