name: CD to CloudRun

on:
  push: 
    tags: 
      - "**"

jobs:
  cd-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4' #GCP required

    - name: 'set version from tag'
      run: |
        echo ${{ github.ref_name }}
        TAG=`echo ${{ github.ref_name }} | sed 's/\./-/g' | awk '{print tolower($0)}'`
        echo $TAG
        echo "TAG=$TAG" >> $GITHUB_ENV

        sed -i "s/{VERSION}/$TAG/g" server/cloudrun.yaml
        cat server/cloudrun.yaml

    - uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: ${{ secrets.GCP_SERVICEACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'pivotalspring-server-prod'
        metadata: server/cloudrun.yaml
        region: us-west1 # Still needed with yaml
        # image: 'docker.io/dbeauregard/pivotalspring-server:0.0.1-SNAPSHOT'

    - name: 'Show output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'

    - name: Set the Summary
      if: always()
      id: set-step-summary
      run: |
        echo "TAG: $TAG"  >> $GITHUB_STEP_SUMMARY
        echo "URL: ${{ steps.deploy.outputs.url }}" >> $GITHUB_STEP_SUMMARY