name: CD to CloudRun

on:
  push: 
    tags: 
      -"**"
    # release:
      # types: [released, edited]

jobs:
  cd-cloudrun:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4' #GCP required

    - uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: ${{ secrets.GCP_SERVICEACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'pivotalspring-prod1'
        region: us-west1
        image: 'docker.io/dbeauregard/pivotalspring-server:0.0.1-SNAPSHOT' #update me to 'latest-ish'
        metadata: server/cloudrun.yaml # create me
        # increase memory and other settings

    - name: 'Show output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'