name: CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Publish jars to GitHub Packages

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Set variables
      run: |
        echo "Build Number: ${{ github.run_number }}"
      
        # Extract the Gradle Version appended with this build/run number
        VERSION=$(./gradlew :pivotalspring-server:properties -Pbuild-number=${{ github.run_number }} | grep version: | cut -d " " -f 2-)
        echo "VERSION: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        # Extract the Gradle Project Name
        NAME=$(./gradlew :pivotalspring-server:properties -Pbuild-number=${{ github.run_number }} | grep name: | cut -d " " -f 2-)
        echo "NAME: $NAME"
        echo "NAME=$NAME" >> $GITHUB_ENV

        echo "DOCKER_NAME=$NAME" >> $GITHUB_ENV
        echo "DOCKER_TAG=$NAME:$VERSION" >> $GITHUB_ENV

    # The heavy lifting of the Build 
    - name: Build (Compile, Assemble, Check, Test)
      run: ./gradlew build --scan -Pbuild-number=${{ github.run_number }}

    - name: Upload Server Jar
      uses: actions/upload-artifact@v4
      with:
        name: Server-BootJar
        path: server/build/libs/pivotalspring-server-*.jar

    - name: Upload Client Jar
      uses: actions/upload-artifact@v4
      with:
        name: Client-BootJar
        path: client/build/libs/pivotalspring-client-*.jar

    - name: Upload SpotBugs
      uses: actions/upload-artifact@v4
      with:
        name: SpotBugs Report
        path: server/build/reports/spotbugs/*.html

    - name: Upload Jacoco
      uses: actions/upload-artifact@v4
      with:
        name: Jacoco Report
        path: server/build/reports/jacoco/test/html
    
    - name: Upload Checkstyle
      uses: actions/upload-artifact@v4
      with:
        name: CheckStyle Report
        path: server/build/reports/checkstyle/*.html

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish -Pbuild-number=${{ github.run_number }}
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build OCI Image 
      run: ./gradlew :pivotalspring-server:bootBuildImag -Pbuild-number=${{ github.run_number }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and Push OCI Image
      run: |
        docker tag ${{ env.DOCKER_TAG }} dbeauregard/${{ env.DOCKER_TAG }}
        docker tag ${{ env.DOCKER_TAG }} dbeauregard/${{ env.DOCKER_NAME }}:CURRENT
        docker push dbeauregard/${{ env.DOCKER_TAG }}
        docker push dbeauregard/${{ env.DOCKER_NAME }}:CURRENT

    - name: Set the Summary
      if: always()
      id: set-step-summary
      run: |
        echo "NAME: $NAME" >> $GITHUB_STEP_SUMMARY
        echo "VERSION: $VERSION" >> $GITHUB_STEP_SUMMARY
        echo "DOCKER-NAME: $DOCKER_NAME" >> $GITHUB_STEP_SUMMARY
        echo "DOCKER-TAG: $DOCKER_TAG" >> $GITHUB_STEP_SUMMARY

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

